### ISSUE TITLE
感觉有些运行库我没装，还有依赖，有没有这方面的教程

### ISSUE THREAD

**Issue by Myosotis6535** [kairui1108/EhuixueAutomatic#2]
感觉有些运行库我没装，还有依赖，有没有这方面的教程

**Comment by Myosotis6535** [comment]
我安完全部运行库和依赖了，成功进入，但还是获取不了在学课程

**Comment by Myosotis6535** [comment]
Traceback (most recent call last):
  File "C:\Users\65352\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\65352\Desktop\EhuixueAutomatic-master\src\videos\AppGui.py", line 141, in get_course
    courses = Helper(config['phone']).get_study_course()
  File "C:\Users\65352\Desktop\EhuixueAutomatic-master\src\exercises\helper.py", line 21, in __init__
    self.login(session_name)
  File "C:\Users\65352\Desktop\EhuixueAutomatic-master\src\exercises\helper.py", line 39, in login
    CkGetter(phone, pwd, loger).post_login(name)
  File "C:\Users\65352\Desktop\EhuixueAutomatic-master\src\exercises\ckGetter.py", line 32, in post_login
    r = res.json()
  File "C:\Users\65352\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Myosotis6535** [comment]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\65352\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\65352\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\65352\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\65352\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\65352\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\65352\Desktop\EhuixueAutomatic-master\src\videos\AppGui.py", line 141, in get_course
    courses = Helper(config['phone']).get_study_course()
  File "C:\Users\65352\Desktop\EhuixueAutomatic-master\src\exercises\helper.py", line 21, in __init__
    self.login(session_name)
  File "C:\Users\65352\Desktop\EhuixueAutomatic-master\src\exercises\helper.py", line 39, in login
    CkGetter(phone, pwd, loger).post_login(name)
  File "C:\Users\65352\Desktop\EhuixueAutomatic-master\src\exercises\ckGetter.py", line 32, in post_login
    r = res.json()
  File "C:\Users\65352\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by kairui1108** [comment]
我用起来没问题，你下载我之前打包好的试试，[https://github.com/kairui1108/EhuixueAutomatic/releases/download/1.2.2/ehx_toolBox.exe](https://github.com/kairui1108/EhuixueAutomatic/releases/download/1.2.2/ehx_toolBox.exe)
